---
development:
  dialect: "sqlite3"
  database: tada_tada_development.sqlite

test:
  dialect: "sqlite3"
  database: tada_tada_test.sqlite

production:
  dialect: "sqlite3"
  database: tada_tada_production.sqlite
